function x_kp1_hat = apply_fast_feedback_correction (x_kp1_bar, v_kp1, delta_T_Rk_clock_rate_offset)
    x_kp1_hat = [];
    x_kp1_hat.time = x_kp1_bar.time;
    x_kp1_hat.position = x_kp1_bar.position + ...
        8.44612e-3 * v_kp1.position + ...
        0.495778 * delta_T_Rk_clock_rate_offset * v_kp1.velocity;
    x_kp1_hat.velocity = x_kp1_bar.velocity + ...
        3.582e-5/delta_T_Rk_clock_rate_offset * v_kp1.position + ...
        0.999979 * v_kp1.velocity;
    x_kp1_hat.acceleration = x_kp1_bar.acceleration + ...
        -3.55164e-5/delta_T_Rk_clock_rate_offset^2 * v_kp1.position + ...
        1.000009/delta_T_Rk_clock_rate_offset * v_kp1.velocity;
    x_kp1_hat.clock_offset = x_kp1_bar.clock_offset + ...
        8.46395e-3 * v_kp1.clock_offset + ...
        2.86552e-6 * delta_T_Rk_clock_rate_offset * v_kp1.clock_rate_offset;
    x_kp1_hat.clock_rate_offset = x_kp1_bar.clock_rate_offset + ...
        2.07034e-10/delta_T_Rk_clock_rate_offset * v_kp1.clock_offset + ...
        0.999997 * v_kp1.clock_rate_offset;
end