function x_kp1_hat = apply_feedback_correction (x_kp1_bar, v_kp1, delta_T_Rk_clock_rate_offset)
    x_kp1_hat = [];
    x_kp1_hat.time = x_kp1_bar.time;
    x_kp1_hat.position = x_kp1_bar.position + ...
        8.44567e-3 * v_kp1.position + ...
        0.508214 * delta_T_Rk_clock_rate_offset * v_kp1.velocity;
    x_kp1_hat.velocity = x_kp1_bar.velocity + ...
        3.67184e-5/delta_T_Rk_clock_rate_offset * v_kp1.position + ...
        0.975104 * v_kp1.velocity;
    x_kp1_hat.acceleration = x_kp1_bar.acceleration + ...
        -3.29082e-5/delta_T_Rk_clock_rate_offset^2 * v_kp1.position + ...
        0.927802/delta_T_Rk_clock_rate_offset * v_kp1.velocity;
    x_kp1_hat.clock_offset = x_kp1_bar.clock_offset + ...
        8.462e-3 * v_kp1.clock_offset + ...
        0.0271035 * delta_T_Rk_clock_rate_offset * v_kp1.clock_rate_offset;
    x_kp1_hat.clock_rate_offset = x_kp1_bar.clock_rate_offset + ...
        1.95823e-6/delta_T_Rk_clock_rate_offset * v_kp1.clock_offset + ...
        0.972659 * v_kp1.clock_rate_offset;
end